///////////////////////////////////////////////////////////
//  Role.cs
//  Implementation of the Enumeration Role
//  Generated by Enterprise Architect
//  Created on:      28-Oct-2017 12:15:33 AM
//  Original author: Max Ermoshyn
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Domain {
	public enum Role : int {

	}//end Role

}//end namespace Domain