//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.MessageQueue {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageQueue.IMessageQueue")]
    public interface IMessageQueue {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageQueue/AddMassage", ReplyAction="http://tempuri.org/IMessageQueue/AddMassageResponse")]
        System.Guid AddMassage(string message, string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageQueue/AddMassage", ReplyAction="http://tempuri.org/IMessageQueue/AddMassageResponse")]
        System.Threading.Tasks.Task<System.Guid> AddMassageAsync(string message, string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageQueue/RemoveMessage", ReplyAction="http://tempuri.org/IMessageQueue/RemoveMessageResponse")]
        bool RemoveMessage(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageQueue/RemoveMessage", ReplyAction="http://tempuri.org/IMessageQueue/RemoveMessageResponse")]
        System.Threading.Tasks.Task<bool> RemoveMessageAsync(System.Guid guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageQueueChannel : IMessageQueue, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageQueueClient : System.ServiceModel.ClientBase<IMessageQueue>, IMessageQueue {
        
        public MessageQueueClient() {
        }
        
        public MessageQueueClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageQueueClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageQueueClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageQueueClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid AddMassage(string message, string parameters) {
            return base.Channel.AddMassage(message, parameters);
        }
        
        public System.Threading.Tasks.Task<System.Guid> AddMassageAsync(string message, string parameters) {
            return base.Channel.AddMassageAsync(message, parameters);
        }
        
        public bool RemoveMessage(System.Guid guid) {
            return base.Channel.RemoveMessage(guid);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveMessageAsync(System.Guid guid) {
            return base.Channel.RemoveMessageAsync(guid);
        }
    }
}
