///////////////////////////////////////////////////////////
//  OrderController.cs
//  Implementation of the Class OrderController
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2017 8:55:21 AM
//  Original author: Max Ermoshyn
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Web.Mvc;
using OOP.Models;
using OOP.Services;

namespace OOP.Controllers
{
    public class OrderController : Controller
    {
        public OrderQueue m_OrderQueue;

        /// <param name="pizza"></param>
        public void AddToCart(Pizza pizza)
        {
        }

        /// <param name="pizza"></param>
        public void RemoveFromCart(Pizza pizza)
        {
        }

        public void Clean()
        {
        }

        public List<Pizza> Index()
        {
            return null;
        }

        /// <param name="order"></param>
        public void CreateOrder(Order order)
        {
        }
    } //end OrderController
} //end namespace View
