///////////////////////////////////////////////////////////
//  PizzaController.cs
//  Implementation of the Class PizzaController
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2017 8:55:21 AM
//  Original author: Max Ermoshyn
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Web.Mvc;
using OOP.Models;
using OOP.Services;

namespace OOP.Controllers
{
    public class PizzaController : Controller
    {
        public PizzaRepository m_PizzaRepository;

        public PizzaController()
        {
            m_PizzaRepository = new PizzaRepository();
        }

        /// <param name="id"></param>
        public Pizza GetPizza(int id)
        {
            return null;
        }

        public ActionResult Index()
        {
            var list = m_PizzaRepository.GetAll();
            return View(list);
        }

        public ActionResult Create()
        {
            return View(new Pizza());
        }

        [HttpPost]
        /// <param name="pizza"></param>
        public ActionResult Create(Pizza pizza)
        {
            try
            {
                m_PizzaRepository.Create(pizza);
                return View("Success");
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }

        /// <param name="pizza"></param>
        public void Delete(Pizza pizza)
        {
        }

        /// <param name="pizza"></param>
        public void Update(Pizza pizza)
        {
        }
    } //end PizzaController
} //end namespace View
