///////////////////////////////////////////////////////////
//  OrderQueue.cs
//  Implementation of the Class OrderQueue
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2017 8:55:21 AM
//  Original author: Max Ermoshyn
///////////////////////////////////////////////////////////

using OOP.Models;

namespace OOP.Services
{
    public class OrderQueue
    {
        ~OrderQueue()
        {
        }

        /// <param name="order"></param>
        public void Enqueue(Order order)
        {
        }

        public Order Dequeue()
        {
            return null;
        }

        public Order Peek()
        {
            return null;
        }

        /// <param name="pizza"></param>
        public void AddToCart(Pizza pizza)
        {
        }

        /// <param name="pizza"></param>
        public void RemoveFromCart(Pizza pizza)
        {
        }
    } //end OrderQueue
} //end namespace DataAccess
