///////////////////////////////////////////////////////////
//  PizzaRepository.cs
//  Implementation of the Class PizzaRepository
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2017 8:55:21 AM
//  Original author: Max Ermoshyn
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Linq;
using OOP.DataAccess.Context;
using OOP.Models;

namespace OOP.Services
{
    public class PizzaRepository
    {

        public OOPDbContext DbContext { get; set; }

        public PizzaRepository()
        {
            DbContext = new OOPDbContext();
        }

        /// <param name="pizza"></param>
        public void Create(Pizza pizza)
        {
            DbContext.Pizzas.Add(pizza);
            DbContext.SaveChanges();
        }

        /// <param name="pizza"></param>
        public void Delete(Pizza pizza)
        {
        }

        /// <param name="id"></param>
        public Pizza Get(int id)
        {
            return null;
        }

        public List<Pizza> GetAll()
        {
            return DbContext.Pizzas.ToList();
        }

        /// <param name="pizza"></param>
        public void Update(Pizza pizza)
        {
        }
    } //end PizzaRepository
} //end namespace DataAccess
