///////////////////////////////////////////////////////////
//  UserRepository.cs
//  Implementation of the Class UserRepository
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2017 8:55:21 AM
//  Original author: Max Ermoshyn
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using OOP.Models;

namespace OOP.Services
{
    public class UserRepository
    {
        ~UserRepository()
        {
        }

        /// <param name="id"></param>
        public User Get(int id)
        {
            return null;
        }

        /// <param name="user"></param>
        public void Create(User user)
        {
        }

        /// <param name="user"></param>
        public void Delete(User user)
        {
        }

        public List<User> GetAll()
        {
            return null;
        }
    } //end UserRepository
} //end namespace DataAccess
