///////////////////////////////////////////////////////////
//  Order.cs
//  Implementation of the Class Order
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2017 8:55:21 AM
//  Original author: Max Ermoshyn
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace OOP.Models
{
    public class Order
    {
        public int Id { get; set; }
        public List<Pizza> List1 { get; set; }
        public User Customer { get; set; }

        ~Order()
        {
        }
    } //end Order
} //end namespace Domain
