///////////////////////////////////////////////////////////
//  Pizza.cs
//  Implementation of the Class Pizza
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2017 8:55:21 AM
//  Original author: Max Ermoshyn
///////////////////////////////////////////////////////////

namespace OOP.Models
{
    public class Pizza
    {
        public int Id { get; set; }

        public int Cost { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }
    } //end Pizza
} //end namespace Domain
