///////////////////////////////////////////////////////////
//  Role.cs
//  Implementation of the Enumeration Role
//  Generated by Enterprise Architect
//  Created on:      11-Nov-2017 8:55:21 AM
//  Original author: Max Ermoshyn
///////////////////////////////////////////////////////////

namespace OOP.Models
{
    public enum Role
    {
        User,
        Admin
    } //end Role
} //end namespace Domain
